FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config libtool gettext libz-dev libpcre2-dev libssl-dev libedit-dev

COPY . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/lib/.libs
